spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/emptimehub_local
    username: postgres
    password: admin

  flyway:
    locations: classpath:db/seed/local,classpath:db/migration
  mail:
    host: smtp.gmail.com
    port: 587
    username: manojkumarmengani281@gmail.com
    password: phxbthxqtttqvswp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
cors:
  allowed-origins: http://localhost:8080
  allowed-methods: GET,POST,PUT,DELETE,OPTIONS
  allowed-headers: "*" # Not used in code anymore directly
  allow-credentials: true
